services:
  server:
    image: michal1112/pyszkomat_backend:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pyszkomat_db
      DB_USER: postgres
      DB_PASSWORD: admin4321
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pyszkomat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin4321
